## 1 - Importar Pandas

In [1]:
import pandas as pd
import numpy as np

## 2 - Cargar datos

In [5]:
df = pd.read_csv("datos_meteorologicos.csv")


In [82]:
df.head()

Fecha  Temperatura  Precipitación    Humedad
0 2010-01-01    17.440675      10.957482  52.384637
1 2010-01-02    25.759468       5.315628  30.633530
2 2010-01-03    20.138169      15.317706  41.496715
3 2010-01-04    17.244159      13.151008  90.684704
4 2010-01-05    11.182740      16.413667  22.116422

## 3 - Exploración Inicial

In [9]:
df.shape

(5110, 4)

In [11]:
df.columns

Index(['Fecha', 'Temperatura', 'Precipitación', 'Humedad'], dtype='object')

In [26]:
df["Fecha"] = pd.to_datetime(df["Fecha"], format = "%d/%m/%Y")

In [28]:
df

Fecha  Temperatura  Precipitación    Humedad
0    2010-01-01    17.440675      10.957482  52.384637
1    2010-01-02    25.759468       5.315628  30.633530
2    2010-01-03    20.138169      15.317706  41.496715
3    2010-01-04    17.244159      13.151008  90.684704
4    2010-01-05    11.182740      16.413667  22.116422
...         ...          ...            ...        ...
5105 2023-12-24    -9.554692      12.700998  50.094533
5106 2023-12-25     2.837831       5.475686  92.456057
5107 2023-12-26    29.873597       4.615012  18.362847
5108 2023-12-27          NaN            NaN        NaN
5109 2023-12-28    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Fecha          5110 non-null   datetime64[ns]
 1   Temperatura    4855 non-null   float64       
 2   Precipitación  4855 non-null   float64       
 3   Humedad        4855 non-null   float64       
dtypes: datetime64[ns](1), float64(3)
memory usage: 159.8 KB


In [38]:
#Convertir las columnas del dataFrame en arrays de Numpy
array_fecha = df["Fecha"].values
array_fecha

array(['2010-01-01T00:00:00.000000000', '2010-01-02T00:00:00.000000000',
       '2010-01-03T00:00:00.000000000', ...,
       '2023-12-26T00:00:00.000000000', '2023-12-27T00:00:00.000000000',
       '2023-12-28T00:00:00.000000000'], dtype='datetime64[ns]')

In [42]:
array_precipitaciones = df["Precipitación"].values
array_precipitaciones

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
               nan,  7.33051023])

In [44]:
array_temperatura = df["Temperatura"].values
array_temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

In [46]:
array_humedad = df["Humedad"].values
array_humedad

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
               nan, 50.64621058])

### Array Temperatura

In [53]:
# Identificar datos faltantes en los array
np.isnan(array_temperatura)

array([False, False, False, ..., False,  True, False])

In [65]:
# Reemplazar datos faltantes por el promedio de los valores
promedio_temperatura = np.nanmean(array_temperatura)
array_temperatura_con_promedio = np.where(np.isnan(array_temperatura), promedio_temperatura, array_temperatura)
array_temperatura_con_promedio

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
       14.88929572, 37.30804318])

### Array Humedad

In [92]:
# Identificar datos faltantes en los array
np.isnan(array_humedad)

array([False, False, False, ..., False, False, False])

In [94]:
# Reemplazar datos faltantes por el promedio de los valores
promedio_humedad = np.nanmean(array_humedad)
array_humedad_con_promedio = np.where(np.isnan(array_humedad), promedio_humedad, array_humedad)
array_humedad_con_promedio

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
       54.3590608 , 50.64621058])

### Array Precipitaciones

In [70]:
# Identificar datos faltantes en los array
np.isnan(array_precipitaciones)

array([False, False, False, ..., False,  True, False])

In [72]:
# Reemplazar datos faltantes por el promedio de los valores
promedio_precipitaciones = np.nanmean(array_precipitaciones)
array_precipitaciones_con_promedio = np.where(np.isnan(array_precipitaciones), promedio_precipitaciones, array_precipitaciones)
array_precipitaciones_con_promedio

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
        9.9016036 ,  7.33051023])

## 4 - Analisis Básico


In [74]:
# Temperatura promedio
array_temperatura_con_promedio.mean()

14.889295723531713

In [78]:
# Total Precipitaciones
array_precipitaciones_con_promedio.sum()

50597.19438939993

In [80]:
# Maxima hummedad registrada
array_humedad_con_promedio.max()

99.99658156071747

In [ ]:
# Fecha mas Calurosa

In [ ]:
# Fecha mas Fria